[workspace]
members = [
    "core",
    "net",
    "store",
    "crypto",
    "sync",
    "ops",
    "pipeline",
    "circles",
    "doc",
    "sdk",
    "config",
    "av",
    "app",
    "tools/gen_baseline",
]
resolver = "2"

[workspace.package]
version = "0.10.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[workspace.dependencies]
zodia-core   = { path = "core" }
zodia-net    = { path = "net" }
zodia-store  = { path = "store" }
zodia-crypto = { path = "crypto" }
zodia-sync   = { path = "sync" }
zodia-ops    = { path = "ops" }
zodia-pipeline = { path = "pipeline" }
zodia-circles = { path = "circles" }
zodia-doc    = { path = "doc" }
zodia-sdk    = { path = "sdk" }
zodia-av     = { path = "av" }

zodia-config = { path = "config" }

sqlx       = { version = "0.8", default-features = false, features = ["runtime-tokio", "sqlite", "macros"] }
toml       = "0.8"
blake3     = "1"
bytes      = "1"
opus       = "0.3"
cpal       = "0.15"
ringbuf    = "0.3"
serde      = { version = "1", features = ["derive"] }
thiserror  = "2"
tokio      = { version = "1", features = ["sync", "rt-multi-thread", "macros"] }
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
x25519-dalek  = { version = "2.0.1", features = ["static_secrets", "getrandom", "reusable_secrets"] }
rand_core  = { version = "0.6", features = ["getrandom"] }
tracing    = "0.1"
dirs       = "5"
ciborium   = "0.2"
